var iFileName = "HumblewoodSpells.js";

SourceList["HW"] = {
	name : "Humblewood",
	abbreviation : "HW",
	group : "Humblewood",
	url : "https://hitpointpress.com/humblewood/"
};

/*
Spells
*/
SpellsList["ambush prey"] = {
	name : "Ambush Prey",
	nameShort : "Ambush Prey",
	source : ["HW", 49],
	defaultExcluded : false,
	classes : ["ranger"],
	level : 2,
	school : "Illus",
	time : "1 a",
	range : "S",
	rangeMetric : "S",
	components : "S,M",
	compMaterial : "a broken twig",
	duration : "1 h",
	description : "invisible for 1hr while unmoving, 1d6 add. dmg on first attack",
	descriptionFull : "You channel primal predatory energies to perfectly conceal your presence in order to surprise your target. You become invisible for the spell's duration, granting advantage on all Dexterity (Stealth) checks to remain hidden. The invisibility will last for the duration of the spell, however, moving 5 feet or more from your position will end the effect. The first attack you make while invisible against any target you are hidden from deals 1d6 additional damage, ending the spell.",
	ritual : false,
	psionic : false,
	allowUpCasting : true,
};

SpellsList["elevated sight"] = {
	name : "Elevated Sight",
	nameShort : "Elevated Sight",
	source : ["HW", 49],
	defaultExcluded : false,
	classes : ["cleric", "druid", "ranger", "warlock", "wizard"],
	level : 1,
	school : "Div",
	time : "1 a",
	range : "S",
	components : "V,S",
	duration : "conc, 1 minute",
	description : "project vision 120 feet up, stays above me, BA to move up or down",
	descriptionFull : "You cast your eyes skyward, granting you sight from a higher vantage point. You project your vision to see through an invisible sensor which appears in a spot up to 120 feet above you. You can see through the sensor as if you were flying, granting a full 360 degree view from its location. The sensor moves with you, retaining its height in relation to you. You can use a bonus action to adjust the sensor’s height, but only to a maximum of 120 feet above you. While looking through this sensor you are blind, though you can switch between seeing through the sensor or through your own eyes at any time during your turn.",
	ritual : false,
	psionic : false,
	allowUpCasting : false,
};

SpellsList["feathered reach"] = {
	name : "Feathered Reach",
	nameShort : "Feathered Reach",
	source : ["HW", 50],
	defaultExcluded : false,
	classes : ["druid", "ranger"],
	level : 3,
	school : "Trans",
	time : "1 a",
	range : "S",
	rangeMetric : "S",
	components : "S,M",
	compMaterial : "a small feather",
	duration : "1 min",
	description : "arms become wings, 2x fly speed, high jump, glide, adv. jump checks",
	descriptionFull : "You transform your arms into powerful wings, and your fingers into long, graceful feathers. The effects of this spell last 1 minute, at which point the feathers gradually fall out, causing you to float gently to the ground as your arms return to their original form. This spell confers a number of benefits upon the caster:\nAs a bonus action, you can fly up to double your movement speed. You must land once you finish your movement, although you do not take fall damage while this spell is active, as your feathered arms bear you gently to the ground.\nYou can use your powerful feathered arms to propel yourself upward a distance equal to half your movement speed. You can do this once during your turn and may use it in conjunction with a regular jump.\nWhen falling, you can use your reaction to stiffen your arms, and glide on the wind. You may fly up to your movement speed, in any direction, choosing where you land.\nYou gain advantage on all athletics checks used to make a long or high jump. You do not need to move 10 feet before you jump to gain distance, and you triple the distance you would jump normally.\nIn order to benefit from this spell your hands must be free of shields and heavy weapons, and you cannot be encumbered.",
	ritual : false,
	psionic : false,
	allowUpCasting : false,
};

SpellsList["globe of twilight"] = {
	name : "Globe of Twilight",
	nameShort : "Gl. of Twilight",
	source : ["HW", 50],
	defaultExcluded : false,
	classes : ["druid", "ranger", "warlock"],
	level : 2,
	school : "Illus",
	time : "1 a",
	range : "S:15-ft radius, 15-ft high",
	components : "V,S,M",
	compMaterial : "a dab of pitch and a bag of glittering sand",
	duration : "conc, 10 min",
	save : "Wis",
	description : "lightly obsc, allies adv stealth, disadv perc, enemies WIS save or blind",
	descriptionFull : "You shroud the area surrounding you in a sphere of night sky, dotted with miniature stars. The twilight conceals your allies, but clearly illuminates your enemies.\nThe area affected by this spell is lightly obscured by magical shadow, within which small constellations softly twinkle. Aside from these stars, only light produced by a spell of 3rd level or higher can properly illuminate any area inside the sphere. Nonmagical light does not function inside the sphere, and all other forms of magical radiance can only produce dim light in a 5-foot space.\nWhen you cast this spell you may designate any number of creatures you can see to be concealed by the supernatural shadows while in the sphere. A concealed creature has advantage on Dexterity (Stealth) checks when inside the sphere and may attempt to hide at any time. Because the area of the spell is lightly obscured, creatures within the spell’s area have disadvantage on Wisdom (Perception) checks made to see those outside of it.\nAll other creatures in the area are dazzled by the light of the miniature stars, causing them to have disadvantage on all perception checks inside the sphere. When such a creature enters the spell’s area for the first time, or starts its turn there, it must make a Wisdom saving throw or be blinded until the end of its turn.",
	ritual : false,
	psionic : false,
	allowUpCasting : true,
};

SpellsList["gust barrier"] = {
	name : "Gust Barrier",
	nameShort : "Gust Barrier",
	source : ["HW", 50],
	defaultExcluded : false,
	classes : ["bard", "druid", "sorcerer", "wizard"],
	level : 0,
	school : "Evoc",
	time : "1 a",
	range : "S",
	rangeMetric : "S",
	components : "S",
	duration : "1 round",
	save : "Con",
	description : "ranged attacks at me at disadv, melee attackers make CON save or flung 10 ft. prone",
	descriptionFull : "You spread your arms wide, allowing yourself to become enveloped by the air around you. Until the end of your next turn, any ranged attack made against you is done with disadvantage.\nMelee attackers who successfully hit you must make a Constitution saving throw against your spell save DC. On a failure, the attacker is flung away from you up to 10 feet and is knocked prone.",
	ritual : false,
	psionic : false,
	allowUpCasting : true,
};

SpellsList["invoke the amarinthine"] = {
	name : "Invoke the Amaranthine",
	nameShort : "Inv. the Amaranthine",
	source : ["HW", 51],
	defaultExcluded : false,
	classes : ["cleric", "paladin"],
	level : 3,
	school : "Div",
	time : "10 min",
	range : "S",
	rangeMetric : "S",
	components : "V,S,M",
	compMaterial : "a holy symbol of the Amaranthine",
	duration : "24 h",
	description : "roll 2d20, keep numbers, replace attack, check, or save within 60 ft as reaction",
	descriptionFull : "You call upon the power of an Amaranthine to grant yourself insight into the Great Rhythm that moves all things. When you cast this spell, roll two d20s, and record what you rolled. For each die, choose either attack roll, skill check, or saving throw. You can choose each option multiple times. For the next 24 hours, you may substitute any roll of an ally or enemy you can see within 60 feet with one of the recorded numbers that matches the type of roll you wish to replace (attack roll, skill check, or saving throw). The target still adds any relevant modifiers to this number, but otherwise treat the substituted number as the number they rolled.\nTo do this, you must spend a reaction to present your holy symbol and invoke the name of the Amaranthine whose energies you called upon. You can do this anytime after the skill check, saving throw or attack has been rolled, but before the outcome of the event has been determined. The spell ends after 24 hours",
	ritual : false,
	psionic : false,
	allowUpCasting : true,
};

SpellsList["shape plants"] = {
	name : "Shape Plants",
	nameShort : "Shape Plants",
	source : ["HW", 51],
	defaultExcluded : false,
	classes : ["bard", "cleric", "druid"],
	level : 4,
	school : "Trans",
	time : "1 a",
	range : "Touch",
	rangeMetric : "Touch",
	components : "V,S",
	duration : "1 h",
	description : "5-foot cube of plants becomes difficult terrain, 2d4 pierc for every 5 ft moved through",
	descriptionFull : "You call upon gentle natural magics to alter the growth of plants. Any plant life you can see within range that fits within a 5-foot cube can take on whatever shape you desire. Additionally, if the plant is a bramble, or capable of growing thorns, you turn the affected area into difficult terrain, causing 2d4 points of piercing damage for every 5 feet moved through the area you shaped. You may also increase or decrease the number of flowers, vines, leaves, thorns, branches, or fruits produced by any plant you shape.\nAfter one hour, the magic of your spell fades, and the plant resumes its normal shape. If you can use speak with plants (or a similar ability) to communicate with the plant, you may persuade it to retain its new form. Different plants have different feelings and attitudes, and if the form is too different from its natural shape it is likely to decline. If the plant accepts, at the GM’s discretion, it will retain the form you have sculpted it into, in which case the effect becomes permanent.\nFor each spell level above 4th, the size of the cube of plant life you can affect increases by an additional 5 feet.",
	ritual : false,
	psionic : false,
	allowUpCasting : true,
};

SpellsList["spiny shield"] = {
	name : "Spiny Shield",
	nameShort : "Spiny Shield",
	source : ["HW", 51],
	defaultExcluded : false,
	classes : ["druid", "ranger", "sorcerer", "wizard"],
	level : 1,
	school : "Abjur",
	time : "1 rea",
	range : "S",
	rangeMetric : "S",
	components : "V,S,M",
	compMaterial : "a small quill",
	duration : "1 rnd",
	description : "barrier reduces melee damage by 2d4, dealing as much pierc. half cover from range",
	descriptionFull : "An ethereal barrier of spikes, made of magical force, interposes itself between you and an attacker. Until your next turn, when you are hit by a melee attack, the barrier reduces the damage your are dealt by 2d4, and deals the same amount of piercing damage to the attacker. The shield is ineffective against ranged attackers, but still provides a +2 bonus to AC (treat as half cover) against them for the duration.\nAt Higher Levels. When you cast this spell using a spell slot above 1st level, increase the spell’s effect by an additional 1d4 for every slot level above 1st.",
	ritual : false,
	psionic : false,
	allowUpCasting : true,
};

SpellsList["stellar bodies"] = {
	name : "Stellar Bodies",
	nameShort : "Stellar Bodies",
	source : ["HW", 52],
	defaultExcluded : false,
	classes : ["cleric", "druid", "sorcerer", "wizard"],
	level : 4,
	school : "Evoc",
	time : "1 a",
	range : "120 ft",
	components : "V,S",
	duration : "1 min",
	save : "Wis",
	description : "melee attack 5 ft makes WIS save or 1d8 rad. dmg. ranged spell for 4d8 rad. dmg, CON save or blind",
	descriptionFull : "You create two small stars that orbit you. They twinkle pleasantly, shedding dim light in a 10-foot radius centered on you. The stars protect you. If a creature within 5 feet of you hits you with a melee attack they must make a Wisdom saving throw or take 1d8 points of radiant damage for each star orbiting you.\nOnce per round, on your turn, you may use your action to cause a star to streak towards an enemy, expending it as it explodes in a blinding flash. Make a ranged spell attack against an enemy within 120 feet, dealing 4d8 points of radiant damage on a hit. The target must then make a Constitution saving throw or be blinded until the start of your next turn.\nThe spell ends when either its duration expires, you fall unconscious, or you have expended all of your stars.\nAt Higher Levels. When you cast this spell using a spell slot above 4th level, you may create one additional star for every two slot levels above 4th. For each additional star orbiting you, the radius of dim light centered on you increases by 5 feet.",
	ritual : false,
	psionic : false,
	allowUpCasting : true,
};

SpellsList["veil of dusk"] = {
	name : "Veil of Dusk",
	nameShort : "Ambush Prey",
	source : ["HW", 52],
	defaultExcluded : false,
	classes : ["druid", "warlock"],
	level : 1,
	school : "Abjur",
	time : "1 bns",
	range : "60 ft",
	components : "V,S,M",
	compMaterial : "a pinch of soot",
	duration : "conc, 10 min",
	description : "1 crea gets +1 AC and adv. on stealth",
	descriptionFull : "You incant towards a creature, cloaking them in a shadowy veil of darkness and silence. The target gains a +1 bonus to their armor class and rolls stealth checks with advantage for the duration of the spell.",
	ritual : false,
	psionic : false,
	allowUpCasting : false,
};
